services:
  api_prod:
    container_name: api_prod
    image: ghcr.io/8odyy/crowdmind-backend-api:latest
    env_file:
      - .env
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - crowdmind_net
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  crowdmind_net:
    external: true
